### ISSUE TITLE
Images generated on wrong folder and duplicated template

### ISSUE THREAD

**Issue by fcalderan** [danielhusar/gulp-local-screenshots#1]
I'm using this plugin after a a site generation with Jekyll.

``` js
gulp.task('screenshots', ["other-previous-task"], function () {
    var lscreen = require('gulp-local-screenshots');
    gulp.src(env + '/*.html')
        .pipe(lscreen({
            width: ['1280', '1024', '768', '600', '480', '320']
        }))
        .pipe(gulp.dest(env + "/screenshots/"));
});
```

where `env` is a valid folder name ("prod") in which there's a single `index.html` file

Result: 
- it creates correctly a `./prod/screenshots` folder but inside there is only a copy of the index.html file inside `./prod`;
- it creates a `./screens` with 6 images but all images contain a "not found" text.

Expecting result:
- It should create only a  `./prod/screenshots` folder with screenshots of the page `./prod/index.html`.

This is the output in console

``` bash
> gulp prod              ~/www/root/project(master✗)@fcalderan-iMac.local
[gulp] Using gulpfile ~/www/root/project/gulpfile.js
[gulp] Starting 'jshint'...
[gulp] Finished 'jshint' after 227 ms
[gulp] Starting 'prod'...
[gulp] Finished 'prod' after 7.85 ms
Configuration file: _config.yml
Configuration file: _config_prod.yml
            Source: ./src
       Destination: ./prod
      Generating... done.


[gulp] Starting 'validate-HTML'...
[gulp] Finished 'validate-HTML' after 165 ms
[gulp] Starting 'prettify'...
[gulp] Finished 'prettify' after 96 ms
[gulp] Starting 'build-sitemap'...
[gulp] Finished 'build-sitemap' after 56 ms
[gulp] Starting 'screenshots'...
[gulp] Finished 'screenshots' after 137 ms
[gulp] Generated sitemap.xml
[gulp] gulp-local-screenshots: ✔ index-320.jpg
[gulp] gulp-local-screenshots: ✔ index-480.jpg
[gulp] gulp-local-screenshots: ✔ index-600.jpg
[gulp] gulp-local-screenshots: ✔ index-768.jpg
[gulp] gulp-local-screenshots: ✔ index-1024.jpg
[gulp] gulp-local-screenshots: ✔ index-1280.jpg
```

**Comment by miroamarillo** [comment]
This maybe is a silly question.  But I have this setup and I get blank png files with not found inside them.  Please help!!

gulp.task('screenshots', function(){
	gulp.src('./dev/*.html')
	.pipe(localScreenshots({
		port: 3009,
		type: 'png',
		folder: dev + "screenshots/"
	}))
});

**Comment by miroamarillo** [comment]
Never mind. Read the above carefully and needed to pass the path option.  Thanks a lot for this!! Amazing stuff!!

**Comment by danielhusar** [comment]
Cool thanks :+1:

**Comment by miroamarillo** [comment]
Sorry to bother gain ;)

If I call the screenshots task inside the watch task it gives me this error:

Error: listen EADDRINUSE

gulp.task('watch', function() {
  // Watch for changes in the html
	gulp.watch(dev + '**/*.*', ['sync']);
	gulp.watch('./jade/**/**/*.jade', ['templates']);
	gulp.watch(dev + '*.html', ['screenshots']);
});

I know there's a problem with the ports but I can't seem to find the solution.  I have this:

gulp.task('screenshots', function(){
	gulp.src(dev + '*.html')
	.pipe(localScreenshots({
		type: 'png',
		path: 'dev',
		protocol: 'http',
		host: 'localhost',
		server: true,
		port: 3009,
		width: ['1320'],
		folder: dev + "screenshots/"
	}))
});

And localhost running on port 3001.  What I want is to generate an updated image each time the html changes.

Any help would be appreciated :)

Thanks!

**Comment by danielhusar** [comment]
I don't really remember how gulp watch works, but I think its running the tasks in parallel so it runs more screenshots tasks at once, which results in this error.

This could be quite tricky as Im not sure how to avoid this.

**Comment by miroamarillo** [comment]
No worries.  Thanks for your help anyway.  I ended up adding the task to the jade watch:

gulp.watch('./jade/**/**/*.jade', ['templates', 'screenshots']);

It works for now but updates every single png.  I will tinker with it and see if I can detect only updated html files and generate png only for the ones that have changed.
