### ISSUE TITLE
weak@0.2.2 install : 'node-gyp rebuild'

### ISSUE THREAD

**Issue by AJtwiss01** [danielhusar/gulp-local-screenshots#4]
I get the following errors when installing the package 

5291 error weak@0.2.2 install: `node-gyp rebuild`
5291 error Exit status 1
5292 error Failed at the weak@0.2.2 install script 'node-gyp rebuild'.
5292 error This is most likely a problem with the weak package,
5292 error not with npm itself.
5292 error Tell the author that this fails on your system:
5292 error     node-gyp rebuild
5292 error You can get their info via:
5292 error     npm owner ls weak
5292 error There is likely additional logging output above.

Have used this for long time started receiving npm errors recently tried reinstalling the package and the following happens

**Comment by danielhusar** [comment]
Hey, thanks, I will take a look tomorrow.

**Comment by danielhusar** [comment]
Hey I just tried id but it works fine.
```bash
$ npm install gulp-local-screenshots
|
> weak@0.2.2 install /Users/danielhusar/Dev/intercom/doc/node_modules/gulp-local-screenshots/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

  CXX(target) Release/obj.target/weakref/src/weakref.o
  SOLINK_MODULE(target) Release/weakref.node
  SOLINK_MODULE(target) Release/weakref.node: Finished
gulp-local-screenshots@2.0.1 node_modules/gulp-local-screenshots
├── through2@0.4.2 (readable-stream@1.0.33, xtend@2.1.2)
├── st@0.2.6 (graceful-fs@1.2.3, mime@1.2.11, negotiator@0.2.8, async-cache@0.1.5, fd@0.0.2)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, through2@0.5.1, dateformat@1.0.11, lodash.template@2.4.1, multipipe@0.1.2)
└── phantom@0.5.7 (shoe@0.0.15, dnode@1.0.5)

$ gulp screens                                                                                                                                      ✘
[13:25:29] Using gulpfile ~/Dev/intercom/doc/gulpfile.js
[13:25:29] Starting 'screens'...
[13:25:29] Finished 'screens' after 20 ms
[13:25:40] gulp-local-screenshots: ✔ index-320.jpg
[13:25:46] gulp-local-screenshots: ✔ index-480.jpg
[13:25:52] gulp-local-screenshots: ✔ index-1000.jpg
[13:25:57] gulp-local-screenshots: ✔ index-1600.jpg
```

What os do you use?
Can you wipe out node_modules and try again?

**Comment by AJtwiss01** [comment]
I am still not able to install using npm install --save-dev gulp-local-screenshots
I tried it with user and root still same error.
I wiped out node_modules and created new test directory installed gulp and then screenshots 
I gave gulp and phantom running globally and local to the project
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/*****/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Users/*****/screentest/node_modules/gulp-local-screenshots/node_modules/phantom/node_modules/dnode/node_modules/weak/.node-gyp"

**Comment by AJtwiss01** [comment]
![screen shot 2015-03-19 at 11 38 15 am](https://cloud.githubusercontent.com/assets/4231658/6738008/77d31aa0-ce2c-11e4-9314-953d7005bcf9.png)

**Comment by danielhusar** [comment]
This looks like you don't have enough rights.
Try to play around with folder where npm caches modules.
Also you are getting this error in `phantom` dependency so try to ask author, he might know more :)

**Comment by AJtwiss01** [comment]
Uninstalled phantom -g and -dev cleaned npm caches for packages running
OS x 10.9.5
node v0.12.0
and npm 2.5.1
Homebrew 0.9.5
i can install other package with out error, could this happen due to the fact I am using the latest versions of node npm and homebrew

**Comment by danielhusar** [comment]
Hey looks like you're right, its failing on `ios.js` and `node 0.12`
I have bumped all the dependencies and should be now fine, as travis passes on all of those.
Try to install new `2.0.2` version.

**Comment by AJtwiss01** [comment]
Thanks it works like a charm. Great utility I use it daily.
