### ISSUE TITLE
Images paired with HTML files in output folder

### ISSUE THREAD

**Issue by tomgenoni** [danielhusar/gulp-local-screenshots#7]
I'm using the following script to point at an existing localhost server:

```
gulp.task('screenshot', function () {
  gulp.src('./build/**/*.html')
  .pipe(localScreenshots({
    server: false,
    port: 3009,
    type: 'png'
   }))
  .pipe(gulp.dest('./screens/'));
});
```

and the output in `screens` looks like:

- file1.png
- file1.html
- file2.png
- file2.html
- ...

Is this expected? Is there a way to prevent the HTML from being copied?

**Comment by danielhusar** [comment]
Hey yep, you can just omit `.pipe(gulp.dest('./screens/'));`
