### ISSUE TITLE
Screenshots are taken way too fast

### ISSUE THREAD

**Issue by miroamarillo** [danielhusar/gulp-local-screenshots#9]
Is there a way to way until the document complete loads to take the screenshot?  I'm getting screenshots that have some elements off just because some styles need to be applied first.  Adding the timeout option just sets a timeout between screenshot to screenshot but doesn't tell panthomjs to wait for the document to load completely before taking the picture.

I was trying to implement something similar to this but can't seem to make it work:

http://stackoverflow.com/questions/11340038/phantomjs-not-waiting-for-full-page-load

**Comment by miroamarillo** [comment]
Nevermind. Issue was resolved.  Thanks! ;)

**Comment by webmix** [comment]
Hi @miroamarillo 

Could you please explain what you did to resolve the issue ?
I am experiencing a similar issue, page screenshot looks "not fully loaded", some elements are strangely positioned

thanks
